config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  root to: 'public/homes#top'
  get 'search' => 'public/searches#search'
  get 'tagsearch/search' => 'public/tagsearches#search'
  get 'genre/search' => 'public/genre_searches#search'


  scope module: :public do
    resources :posts do
      resource :bookmarks, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update] do
      resources :bookmarks, only: [:index]
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    root to: 'users#index'
    resources :users, only: [:show, :edit, :update, :destroy]
    resources :posts, only: [:show, :index, :destroy]
    resources :post_comments, only: [:index, :destroy]
    resources :genres, only: [:create, :index, :edit, :update]
  end

  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :posts, dependent: :destroy
  validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def create
    @genre = Genre.new(genre_params)
    @genres = Genre.all
    if @genre.save
      redirect_to admin_genres_path
    else
      redirect_to admin_genres_path
      # render :index
    end
  end

  def index
    @genre = Genre.new
    @genres = Genre.all.order(created_at: :desc).page(params[:page]).per(7)
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end


end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container mt-5">
  <div class="row justify-content-center align-items-center">
    <div class="text-center">
      <h3>ジャンル編集</h3>

      <% if @genre.errors.any? %>
          <%= @genre.errors.count %> 件のエラーが発生しました
          <ul>
            <% @genre.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
      <% end %>

      <div class="my-4">
        <%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
          <%= f.label :ジャンル名 %>
          <%= f.text_field :name %>
          <%= f.submit "編集する", class:"mt-2" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
    <div class="text-center">
      <h3>ジャンル一覧・追加</h3>

      <% if @genre.errors.any? %>
          <%= @genre.errors.count %> 件のエラーが発生しました
          <ul>
            <% @genre.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
      <% end %>

      <div class="my-4">
        <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
          <%= f.label :ジャンル名 %>
          <%= f.text_field :name %>
          <%= f.submit "ジャンル追加", class:"mt-2" %>
        <% end %>
      </div>
    </div>
  </div>

    <div class="row justify-content-center mt-4">
      <div class="col-md-6">
        <table class="table" rules="rows" border="3">
          <thead style="background-color: #DDDDDD;">
            <tr>
              <th class="text-center" colspan="2">ジャンル</th>
            </tr>
          </thead>
          <tbody>
            <% @genres.each do |genre| %>
            <tr>
              <td class="col-md-4 text-md-center info"><%= genre.name %></td>
              <td class="col-md-8">
                <div class="d-flex justify-content-center">
                  <%= link_to '編集', edit_admin_genre_path(genre), class:"btn btn-warning btn-sm" %>
                </div>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class="paginate">
          <%= paginate @genres %>
        </div>
      </div>
    </div>
</div>