config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  root to: 'public/homes#top'
  get 'search' => 'public/searches#search'
  get 'tagsearch/search' => 'public/tagsearches#search'
  get 'genre/search' => 'public/genre_searches#search'


  scope module: :public do
    resources :posts do
      resource :bookmarks, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update] do
      resources :bookmarks, only: [:index]
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    root to: 'users#index'
    resources :users, only: [:show, :edit, :update, :destroy]
    resources :posts, only: [:show, :index, :destroy]
    resources :post_comments, only: [:index, :destroy]
    resources :genres, only: [:create, :index, :edit, :update]
  end

  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :comment, presence: true, length: { maximum: 70 }
end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @post_comments = PostComment.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  def destroy
    post_comment = PostComment.find(params[:id])
    post_comment.destroy
    redirect_to request.referer
  end

end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/views/admin/post_comments/index.html.erb
<div class="container mt-5">
  <h3 class="text-center">投稿コメント一覧</h3>
    <div class="row">
      <div class="col-md-12">
        <table class="table mt-3">
          <thead>
            <tr style="background-color: #DDDDDD;">
              <th class="col-md-3">ユーザー名</th>
              <th class="col-md-6">コメント</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @post_comments.each do |comment| %>
            <tr>
              <td><%= comment.user.name %></td>
              <td class="comment"><%= simple_format(comment.comment) %></td>
              <td><%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
              <td>
                <%= link_to '削除', admin_post_comment_path(comment), method: :delete, "data-confirm" => "コメントを削除しますか？", class:"btn btn-danger btn-sm" %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class="paginate">
          <%= paginate @post_comments %>
        </div>
      </div>
    </div>
</div>