config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  root to: 'public/homes#top'
  get 'search' => 'public/searches#search'
  get 'tagsearch/search' => 'public/tagsearches#search'
  get 'genre/search' => 'public/genre_searches#search'


  scope module: :public do
    resources :posts do
      resource :bookmarks, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update] do
      resources :bookmarks, only: [:index]
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    root to: 'users#index'
    resources :users, only: [:show, :edit, :update, :destroy]
    resources :posts, only: [:show, :index, :destroy]
    resources :post_comments, only: [:index, :destroy]
    resources :genres, only: [:create, :index, :edit, :update]
  end

  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :posts, dependent: :destroy
  has_one_attached :profile_image
  has_many :bookmarks, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  validates :name, presence: true, length: { in: 1..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def user_status
    if is_active == true
      "有効"
    else
      "無効"
    end
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id).order(created_at: :desc).page(params[:page]).per(5)
  end

  def index
    @users = User.page(params[:page]).per(10)
    # ↑@users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to admin_user_path(user)
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to admin_root_path
  end

  private

  def user_params
    params.require(:user).permit(:is_active)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def guest_sign_in
    user = User.guest
    sign_in user
    # ゲストユーザーをログイン状態にする
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def edit
  end

  def update
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container mt-5">
  <h4 class="text-center"><%= @user.name %> さんのユーザーステータス変更</h4>
    <div class="row justify-content-center">
      <div class="col-md-6">
        <%= form_with model: @user, url: admin_user_path(@user), method: :patch do |f| %>
        <table class="table mt-3" rules="rows" border="3">
          <tbody>
            <tr>
              <th class="col-md-4" style="background-color: #DDDDDD;">ユーザーID</th>
              <td class="col-md-2"></td>
              <td><%= @user.id %></td>
            </tr>
            <tr>
              <th style="background-color: #DDDDDD;">ユーザー名</th>
              <td></td>
              <td><%= @user.name %></td>
            </tr>
            <tr>
              <th style="background-color: #DDDDDD;">メールアドレス</th>
              <td></td>
              <td><%= @user.email %></td>
            </tr>
            <tr>
              <th style="background-color: #DDDDDD;">ステータスの変更</th>
              <td></td>
              <td>
                <%= f.radio_button :is_active, :true %>
                <%= f.label :is_active_true, "有効" %>
                <%= f.radio_button :is_active, :false %>
                <%= f.label :is_active_false, "無効" %><br>
                <%= f.submit "変更する", class:"btn btn-warning btn-sm", "data-confirm" => "ステータスを変更しますか？" %>
              </td>
            </tr>
        <% end %>
        <%= form_with model: @user, url: admin_user_path(@user), method: :delete do |f| %>
            <tr>
              <th style="background-color: #DDDDDD;">ユーザーの削除</th>
              <td></td>
              <td>
                <%= f.submit "削除する", class:"btn btn-danger", "data-confirm" => "ユーザーを削除しますか？" %>
              </td>
            </tr>
          </tbody>
        </table>
        <% end %>
      </div>
    </div>
</div>

app/views/admin/users/index.html.erb
<div class="container mt-5">
  <h3 class="text-center">ユーザー一覧</h3>
    <div class="row">
      <div class="col-md-12">
        <table class="table mt-3">
          <thead>
            <tr style="background-color: #DDDDDD;">
              <th>ユーザーID</th>
              <th class="col-md-3">ユーザー名</th>
              <th class="col-md-4">メールアドレス</th>
              <th>ユーザーステータス</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td>
                <%= link_to admin_user_path(user) do %>
                  <%= user.name %>
                <% end %>
              </td>
              <td><%= user.email %></td>
              <td><%= user.user_status %></td>
              <!--user_statusはUserモデルに定義してある-->
              <td><%= link_to '変更', edit_admin_user_path(user), class:"btn btn-warning btn-sm" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class="paginate">
          <%= paginate @users %>
        </div>
      </div>
    </div>
</div>

app/views/admin/users/show.html.erb
<!--このページでステータス変更する-->
<div class="container mt-4">
  <h4 class="text-center"><%= @user.name %> さんの詳細</h4>
    <div class="row justify-content-center">
      <div class="col-md-5">
        <table class="table mt-3" rules="rows" border="3">
          <tbody>
            <tr>
              <th class="col-md-3" style="background-color: #DDDDDD;">ユーザーID</th>
              <td class="col-md-3"></td>
              <td><%= @user.id %></td>
            </tr>
            <tr>
              <th style="background-color: #DDDDDD;">ユーザー名</th>
              <td><%= image_tag @user.get_profile_image(60, 60) %></td>
              <td>
                <%= @user.name %>
              </td>
            </tr>
            <tr>
              <th style="background-color: #DDDDDD;">メール<br>アドレス</th>
              <td></td>
              <td><%= @user.email %></td>
            </tr>
            <tr>
              <th style="background-color: #DDDDDD;">ユーザー<br>ステータス</th>
              <td></td>
              <td><%= @user.user_status %></td>
            </tr>
            <tr>
              <th style="background-color: #DDDDDD;">ステータス変更</th>
              <td></td>
              <td><%= link_to '変更する', edit_admin_user_path(@user), class:"btn btn-warning btn-sm" %></td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="col-md-10">
        <table class="table mt-4">
          <thead>
            <tr style="background-color: #DDDDDD;">
              <th>タイトル</th>
              <th class="col-md-2">タグ</th>
              <th class="col-md-2">ジャンル</th>
              <th>Text</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @posts.each do |post| %>
            <tr>
              <td>
                <%= link_to admin_post_path(post) do %>
                  <%= truncate(post.title, length: 10, omision: "...") %>
                <% end %>
              </td>
              <td><%= post.category %></td>
              <td><%= post.genre.name %></td>
              <td><%= truncate(post.body, length: 15, omision: "...") %></td>
              <td><%= post.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class="paginate">
          <%= paginate @posts %>
        </div>
      </div>
    </div>
</div>