config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  root to: 'public/homes#top'
  get 'search' => 'public/searches#search'
  get 'tagsearch/search' => 'public/tagsearches#search'
  get 'genre/search' => 'public/genre_searches#search'


  scope module: :public do
    resources :posts do
      resource :bookmarks, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update] do
      resources :bookmarks, only: [:index]
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    root to: 'users#index'
    resources :users, only: [:show, :edit, :update, :destroy]
    resources :posts, only: [:show, :index, :destroy]
    resources :post_comments, only: [:index, :destroy]
    resources :genres, only: [:create, :index, :edit, :update]
  end

  devise_scope :user do
    post 'users/guest_sign_in' => 'users/sessions#guest_sign_in'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
  #あるユーザーは、ある投稿に対して一意=ある投稿に対してブクマは1回
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :posts, dependent: :destroy
  validates :name, presence: true
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_one_attached :post_image
  has_many :bookmarks, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  belongs_to :genre

  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 250 }
  validates :category, presence: true
  validates :genre_id, presence: true

  def self.search_for(word, method)
    if method == 'perfect'
      Post.where('title LIKE ? OR body LIKE ? OR category LIKE ? OR genre_id IN (SELECT id FROM genres WHERE name LIKE ?)', word, word, word, word)
    elsif method == 'forward'
      Post.where('title LIKE ? OR body LIKE ? OR category LIKE ? OR genre_id IN (SELECT id FROM genres WHERE name LIKE ?)', word + '%', word + '%', word + '%', word + '%')
    elsif method == 'backward'
      Post.where('title LIKE ? OR body LIKE ? OR category LIKE ? OR genre_id IN (SELECT id FROM genres WHERE name LIKE ?)', '%' + word, '%' + word, '%' + word, '%' + word)
    else method == 'partial'
      Post.where('title LIKE ? OR body LIKE ? OR category LIKE ? OR genre_id IN (SELECT id FROM genres WHERE name LIKE ?)', '%' + word + '%', '%' + word + '%', '%' + word + '%', '%' + word + '%')
    end
  end

  def get_post_image
    post_image.variant(resize_to_limit: [350, 200]).processed
  end

  def bookmarked_by?(user)
    bookmarks.exists?(user_id: user)
  end
#ブクマが既にされているか(bookmarked_by?)のメソッドを定義している

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :comment, presence: true, length: { maximum: 70 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :posts, dependent: :destroy
  has_one_attached :profile_image
  has_many :bookmarks, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  validates :name, presence: true, length: { in: 1..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def user_status
    if is_active == true
      "有効"
    else
      "無効"
    end
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @posts = Post.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_posts_path
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id).order(created_at: :desc).page(params[:page]).per(5)
  end

  def index
    @users = User.page(params[:page]).per(10)
    # ↑@users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to admin_user_path(user)
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to admin_root_path
  end

  private

  def user_params
    params.require(:user).permit(:is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :configure_permitted_parameters, if: :devise_controller?

  # protected

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new
    @post.user_id = current_user.id
    @post.save
    # redirect_to 一覧ページ
  end

  def show
  end

  def index
  end

  def edit
  end
  
  def update
  end
  
  def destroy
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def edit
  end

  def update
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>Take.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark mb-3 py-3" style="background-color: #0e357f;">
    <div class="container">
      <a class="navbar-brand" href="/">
        <span><h2>推し活コミュ!!</h2></span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li>
            <%= link_to admin_root_path, class:"nav-link text-light" do %>
              <i class="fa-solid fa-users"></i> ユーザー一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_posts_path, class:"nav-link text-light" do %>
              <i class="fa-solid fa-paste"></i> 投稿一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_post_comments_path, class:"nav-link text-light" do %>
              <i class="fa-solid fa-comments"></i> 投稿コメント一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_genres_path, class:"nav-link text-light" do %>
              <i class="fa-solid fa-face-smile"></i> ジャンル一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete, class:"nav-link text-light" do %>
              <i class="fa-solid fa-right-from-bracket"></i> ログアウト
            <% end %>
          </li>

        <% elsif user_signed_in? %>
          <li>
            <%= link_to user_path(current_user), class:"nav-link text-light" do %>
              <i class="fa-solid fa-user"></i> My page
            <% end %>
          </li>
          <li>
            <%= link_to posts_path, class:"nav-link text-light" do %>
              <i class="fa-solid fa-paste"></i> Post一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
              <i class="fa-solid fa-right-from-bracket"></i> ログアウト
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
              <i class="fa-solid fa-user-plus"></i> 新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path, class:"nav-link text-light" do %>
              <i class="fa-solid fa-right-to-bracket"></i> ログイン
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PF</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/a053787443.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <%= flash[:notice] %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>